apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-timeout
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 20
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s
