apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-503
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 10
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
  httpFault:
    abort:
      percent: 50
      httpStatus: 503
